// let name1 : string = 'Hamza';
// const age  ='23';
// var marraige = 'false';
console.log('Hello world');
var numberOfFaculty = 4;
var numberOfManagment = 3;
var numberOfAbsentFaculty = 2;
var totalNumberOfFaculty = numberOfFaculty * 21;
var biryaniForOnePerson = 42 / totalNumberOfFaculty;
console.log(biryaniForOnePerson);
var weightInKg = 70;
var heightInMeters = 1.75;
var bmi = weightInKg / (heightInMeters * heightInMeters);
console.log("your BMI is ".concat(bmi));
var firstName = 'Hamza';
var age = 23;
var message = "Hello my name is: " + firstName + " and my age is: " + age;
console.log("Hello my name is ".concat(firstName, " and My age is ").concat(age));
var index = 10;
console.log(index);
var a = 5;
var b = 8;
var c = 6;
//             11    +   12    + 8 +  11    - 2 
var result = ++index + ++index + 8 + --index - 2;
console.log(result);
var message1 = 'Hello world';
var num = 20;
num += 2;
num -= 2;
// num = num -2
var num1 = 33;
var num2 = 34;
console.log(num1 == num2);
console.log(num1 != num2);
console.log(num1 > num2);
console.log(num1 < num2);
var age1 = 18;
console.log(age1 >= 18);
